# Generated by Django 4.2.7 on 2023-12-19 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_alter_task_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned',
        ),
        migrations.RemoveField(
            model_name='task',
            name='file_attachment',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
