# Generated by Django 4.2.7 on 2023-12-22 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskstatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskstatus',
            unique_together={('owner', 'task')},
        ),
    ]
